name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.name "MateusAugustoo"
          git config --global user.email "mateusaugusto2017pp@gmail.com"

      - name: Fetch from GitLab and Merge
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/MateusAugustoo/Stock.git
          git fetch gitlab
          git merge gitlab/main --allow-unrelated-histories || true
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      - name: Push to GitLab
        run: |
          git push gitlab main
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
